[project]
name = "insights-from-apple-health"
version = "0.1.0"
description = ""
authors = [
    { name = "DevButter", email = "marknotas@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bs4 (>=0.0.2,<0.0.3)",
    "pandas (>=3.0.3,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "lxml (>=6.1.1,<7.0.0)"
]

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "ipykernel (>=7.3.0,<8.0.0)",
    "mypy (>=2.1.0,<3.0.0)",
    "pyright (>=1.1.410,<2.0.0)"
]

[tool.poetry]
packages = [
    { include = "config", from = "app" },
    { include = "parser", from = "app" }
]

[tool.pyright]
include = ["app", "notebooks"]
extraPaths = ["app"]
pythonVersion = "3.12"
typeCheckingMode = "basic"

[tool.mypy]
python_version = "3.12"
mypy_path = "app"
strict = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

pythonpath=["."]
testpaths = ["tests"]
collect_imported_tests = false
addopts="-ra -vv"
norecursedirs = [
    ".git",
    ".venv",
    ".mypy_cache",
    ".pytest_cache",
    "__pycache__"
]