from dataclasses import dataclass, field


@dataclass(slots=True)
class HealthRecord:
    """Domain object produced by the XML parser.

    `id` is reserved for the database primary key.
    `export_record_index` is generated by the parser while streaming the XML.
    `record_hash` is generated from stable record attributes for idempotency.
    """

    type: str | None
    source_name: str | None
    source_version: str | None
    device: str | None
    unit: str | None
    creation_date: str | None
    start_date: str | None
    end_date: str | None
    value: str | None
    value_numeric: float | None
    id: int | None = None
    export_record_index: int | None = None
    record_hash: str | None = None
    metadata: dict[str, str] = field(default_factory=dict)


@dataclass(slots=True)
class HealthRecordEvent:
    """A parsed record plus the parse run that produced it."""

    run_id: int
    health_record: HealthRecord
